### ISSUE TITLE
Criar interface com o usuário.

### ISSUE THREAD

**Issue by Hargre** [BDD-OperationalProfile/trace_feature#10]
Definir os comandos a serem utilizados pelo usuário para utilizar a biblioteca. Por exemplo:

trace_feature --file <caminho do arquivo.feature>
trace_feature --file <caminho do arquivo.feature> --scenario <nome/linha do cenário>

**Comment by RafaelFazzolino** [comment]
Utilizar esta lib: http://click.pocoo.org/5/

A utilização desta lib (ou alguma muito próxima) é **essencial** pois a mesma vai facilitar a documentação da interface, além da possibilidade de definição de alias e autocomplete no terminal..
